### ISSUE TITLE
TPCH Query 9 wrong Query Plan

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb_delta#1]
it seems duckdb delta  (0.10.3.dev1012,  as i could not installed the latest nightly build )  is generating a less optimized plan for Query 9

see example  https://colab.research.google.com/drive/1_azbqz7v7_VVfpk4qPhcIRtvxNTquXfL#scrollTo=mAsEG6aOqTuD

<img width="991" alt="image" src="https://github.com/duckdb/duckdb_delta/assets/12554469/d0972f03-f13a-480c-a920-61d62edecd25">

**Comment by samansmink** [comment]
Hi @djouallah thanks for reporting! both column statistics and cardinality estimation for delta are not yet implemented, so implementing those should probably resolve this issue. If not, I will take a deeper look at this

**Comment by djouallah** [comment]
is this the right way to install delta

```
duckdb.sql(" SET custom_extension_repository = 'http://nightly-extensions.duckdb.org'; ")
duckdb.sql(" install delta")
duckdb.sql(" load delta")
```

**Comment by samansmink** [comment]
More docs are on the way, but this will work now:

```SQL
INSTALL delta
```

to overwrite an already install delta extension:

```SQL
FORCE INSTALL delta
```

to install the nightly build there's an alias now:
```SQL
INSTALL delta FROM core_nightly
```

However, note that the delta extension is now autoloadable, so just typing:

```
from delta_scan("....")
```
should also work

**Comment by samansmink** [comment]
Also fyi: https://github.com/duckdb/duckdb_delta/issues/8

**Comment by djouallah** [comment]
it is way better now thanks
