### ISSUE TITLE
INTERNAL Error: Vector::Reference used on vector of different type

### ISSUE THREAD

**Issue by eichert12** [duckdb/duckdb_delta#105]
I received an internal error regarding "Vector::Reference used on vector of different type" when trying to query a table in Databricks via the uc_catalog and delta_scan extensions.

INSTALL uc_catalog from core_nightly;
INSTALL delta from core_nightly;
LOAD delta;
LOAD uc_catalog;
 
CREATE SECRET (
      TYPE UC,
      TOKEN ‘XXXXX',
      ENDPOINT 'https://adb-4772174085251619.19.azuredatabricks.net'
  );
 
CREATE SECRET (
      TYPE AZURE,
      PROVIDER CREDENTIAL_CHAIN,
      CHAIN 'cli'
  );
 
ATTACH 'workspace_XXXX' AS workspace_XXXX (TYPE UC_CATALOG);
 
select * from workspace_XXXX.schema.table limit 10;

As an aside I also always get this message on first query issues: "Not implemented Error: Tried to fallback to unknown type for 'timestamp_ntz'"

**Comment by samansmink** [comment]
Thanks for reporting @eichert12, however this is an issue with the uc_catalog extension. Since that extension is experimental and its type support is pretty minimal in its current state, im closing this issue.
