### ISSUE TITLE
Record Batch Reader is slow

### ISSUE THREAD

**Issue by alexandermorozov** [duckdb/duckdb_delta#107]
Hey folks!

I'm trying to do streaming processing of a delta dataset while reading it from S3. Here are 2 variants of the code:
```
TEN_GIG = "select * from delta_scan('s3://....')

# first version
conn = duckdb.connect()
res = conn.query(TEN_GIG)
reader = res.fetch_arrow_reader(batch_size=1_000_000)
for batch in reader:
    df = polars.from_arrow(batch)
    print('got a batch', len(df))

# second version
 duckdb.execute(TEN_GIG)
 results = duckdb.fetch_record_batch(1_000_000)
 while 1:
     try:
         batch = results.read_next_batch()
         df = polars.from_arrow(batch)
         print('got a batch', len(df))
         
    except StopIteration:
        print('done')
        break
``` 

I'm oberving network rates around 20MB/s. Comparatively if I try to fetch all data at once with `duckdb.sql(TEN_GIG).pl()`, download is really fast at >500MB/s.

My hunch is that in the batch mode duckdb is downloading files sequentially to make sure that mem usage stays as low as possible. I didn't found a place in the code where the decision on what to fetch is made.

I'd appreciate any help on this! Anything from solution to where to look in the code.

**Comment by alexandermorozov** [comment]
Thank you, @samansmink ! We've decided to go with a different implementation. I'm not sure if it's best to close the issue or if you prefer to leave it open.

**Comment by samansmink** [comment]
Thanks for checking back @alexandermorozov! I will close this for now then.
