### ISSUE TITLE
An error occurred while trying to automatically install the required extension 'delta'

### ISSUE THREAD

**Issue by mvilrokx** [duckdb/duckdb_delta#2]
Now that DuckDB `v0.10.3` has been released, I am trying to use this extension, but I receive the following error:

```
DuckDB Error

duckdb error: An error occurred while trying to automatically install the required extension 'delta':
Failed to download extension "delta" at URL "http://extensions.duckdb.org/v0.10.3/linux_arm64/delta.duckdb_extension.gz"

Candidate extensions: "md", "inet"

This may be triggered by:
Issue 1002 - The database returned an unexpected error. 
```

I am on an Apple M1. Trying to run this through Superset which is running inside a Docker container.

**Comment by mvilrokx** [comment]
I also tried "plain" duckdb from the CLI:

```
Extension Autoloading Error: An error occurred while trying to automatically install the required extension 'delta':
Failed to download extension "delta" at URL "http://extensions.duckdb.org/v0.10.3/osx_arm64/delta.duckdb_extension.gz"

Candidate extensions: "md", "inet"
```

Same issue, just a different architecture-version.

**Comment by samansmink** [comment]
@mvilrokx The extension was not yet uploaded, it should be available now!

**Comment by mvilrokx** [comment]
I am still seeing the issue on `linux_arm64`:

```
DuckDB Error

duckdb error: An error occurred while trying to automatically install the required extension 'delta':
Failed to download extension "delta" at URL "http://extensions.duckdb.org/v0.10.3/linux_arm64/delta.duckdb_extension.gz"

Candidate extensions: "md", "inet"

```

**Comment by samansmink** [comment]
ah my bad i did not fully read your error message, the extension is not yet supported on `linux_arm64` as stated in the [README](https://github.com/duckdb/duckdb_delta). I've opened an issue for this to track progress: https://github.com/duckdb/duckdb_delta/issues/10

**Comment by samansmink** [comment]
arm binaries are available from nightly now: `force install delta from core_nightly`
