### ISSUE TITLE
Cant connect with azure extension to azure blob store

### ISSUE THREAD

**Issue by nfoerster2** [duckdb/duckdb_delta#30]
I'm doing that SQL below, but its complaining about the account_name which is part of the created secret, what am I doing wrong? 

Tested with:
az://, abfs://, abfss://, azure://

but I always get the issue:
`SQL Error: java.sql.SQLException: IO Error: Hit DeltaKernel FFI error (from: While trying to read from delta table: 'az://deltalake/articles/'): Hit error: 8 (ObjectStoreError) with message (Error interacting with object store: Generic MicrosoftAzure error: Account must be specified)`

```
INSTALL delta;
LOAD delta;
INSTALL azure;
LOAD azure;

CREATE SECRET (
    TYPE AZURE,
    PROVIDER CREDENTIAL_CHAIN,
    CHAIN 'cli;env',
    ACCOUNT_NAME 'testsaweud'
);

select
    *
from
    delta_scan('az://deltalake/articles')
```

```
select
    *
from
    delta_scan('az://testsaweud.blob.core.windows.net/deltalake/articles')
```

`SQL Error: java.sql.SQLException: IO Error: Hit DeltaKernel FFI error (from: While trying to read from delta table: 'az://testsaweud.blob.core.windows.net/deltalake/articles/'): Hit error: 8 (ObjectStoreError) with message (Error interacting with object store: Generic MicrosoftAzure error: URL did not match any known pattern for scheme: az://testsaweud.blob.core.windows.net/deltalake/articles/)`

**Comment by nfoerster2** [comment]
I think its a duplicate to: https://github.com/duckdb/duckdb_delta/issues/21

**Comment by samansmink** [comment]
PR is up https://github.com/duckdb/duckdb_delta/pull/39

**Comment by nfoerster2** [comment]
I will close as it is a duplicate to:
https://github.com/duckdb/duckdb_delta/issues/21
