### ISSUE TITLE
build error with delta extension

### ISSUE THREAD

**Issue by huaxk** [duckdb/duckdb_delta#47]
I want to build duckdb with delta extension:
```
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXTENSIONS='parquet;jemalloc;httpfs;delta'
GEN=ninja make
```
the following error occurs：
```
Scanning dependencies of target delta_kernel
[  2%] Completed 'delta_kernel'
[  3%] Built target delta_kernel
Scanning dependencies of target delta_loadable_extension
[  3%] Building CXX object extension/delta/CMakeFiles/delta_loadable_extension.dir/src/delta_extension.cpp.o
[  3%] Building CXX object extension/delta/CMakeFiles/delta_loadable_extension.dir/src/delta_functions.cpp.o
[  3%] Building CXX object extension/delta/CMakeFiles/delta_loadable_extension.dir/src/delta_utils.cpp.o
[  4%] Building CXX object extension/delta/CMakeFiles/delta_loadable_extension.dir/src/functions/delta_scan.cpp.o
make[2]: *** No rule to make target 'rust/src/delta_kernel/target/x86_64-unknown-linux-gnu/release/libdelta_kernel_ffi.a', needed by 'extension/delta/delta.duckdb_extension'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:8506: extension/delta/CMakeFiles/delta_loadable_extension.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Did I go wrong somewhere?

**Comment by samansmink** [comment]
HEy @huaxk, can you just run the `GEN=ninja make` without the line before? letting the makefile generate the correct CMake command is the easiest. It's also how our [CI](https://github.com/duckdb/extension-ci-tools/blob/71b8a603ea24b1ac8a2cff134aca28163576548f/.github/workflows/_extension_distribution.yml) builds extensions

**Comment by huaxk** [comment]
Thanks for your answer！

**Comment by huaxk** [comment]
The reason for the error above has been found, it is set in my cargo config file: 
```
[build]
target-dir = "~/.cargo/target"
```
cargo compiles to another directory, so can not find `'rust/src/delta_kernel/target/x86_64-unknown-linux-gnu/release/libdelta_kernel_ffi.a'` .

**Comment by huaxk** [comment]
Also need to add env:
```
export OPENSSL_USE_STATIC_LIBS=true
export OPENSSL_INCLUDE_DIR=~/duckdb_delta/build/release/vcpkg_installed/x64-linux/include
export OPENSSL_DIR=~/duckdb_delta/build/release/vcpkg_installed/x64-linux
```
specify the openssl installation directory by vcpkg, cargo will use it when compile delta_kernel, otherwise there will be an error when linking.

**Comment by huaxk** [comment]
Ok!

**Comment by samansmink** [comment]
Thanks @huaxk for reporting back your findings!
