### ISSUE TITLE
Schema error: No such field: deletionVector

### ISSUE THREAD

**Issue by adzeeman** [duckdb/duckdb_delta#48]
Hi team,

I'm using DuckDB version: `v1.0.0 1f98600c2c`

This is the query I run:
```sql
CREATE SECRET (
      TYPE S3,
      PROVIDER CREDENTIAL_CHAIN
  );
SELECT * FROM delta_scan('s3://private-bucket/folder/');
```

Exception:
```
IO Error: Hit DeltaKernel FFI error (from: While trying to read from delta table: 's3://private-bucket/folder/''): Hit error: 2 (ArrowError) with message (Schema error: No such field: deletionVector)
```

The Delta table content was created using the [Flink Delta connector](https://github.com/delta-io/delta/tree/master/connectors/flink), which uses Delta standalone.

Using Spark, I'm able to query the Delta table.

I tested the query with Delta tables created with other connectors, and they worked fine.  Perhaps this is a [delta-rs](https://github.com/delta-io/delta-rs) issue.

**Comment by adzeeman** [comment]
I'm closing this issues as I've had trouble re-creating it.

**Comment by samansmink** [comment]
Thanks @adzeeman I know about this issue, see https://github.com/delta-incubator/delta-kernel-rs/issues/261.

I have this on my radar, while it might be partially fixed currently, I will need to do some proper testing. If you run into it again please don't hesitate to reopen!
