### ISSUE TITLE
InternalException: INTERNAL Error: Attempted to dereference shared_ptr that is NULL! when filtering on partition column

### ISSUE THREAD

**Issue by asbonatto** [duckdb/duckdb_delta#56]
Hello.  I'm using the extension to query a delta table but strangely it raises an exception when I try to filter on the partition column.
This works perfectly:

```
with duckdb.connect() as con:
    con.sql("""
    select * from delta_scan('D:/datasets/table) limit 100
    """).show()
```

but this

```
with duckdb.connect() as con:
    con.sql("""
    select * from delta_scan('D:/datasets/table) where dt_ref = '2024-07-17' limit 100
    """).show()
```
throws
````InternalException: INTERNAL Error: Attempted to dereference shared_ptr that is NULL!
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

I'm using Windows 10, duckdb 1.0.0

**Comment by watsy0007** [comment]
i got the same error.

**Comment by watsy0007** [comment]
I try execute two queries

1. `select * from delta_scan('s3://path')  where  month=202405 and unique_id = 'uid1' limit 20` 
2. `select * from delta_scan('s3://path')  where unique_id = 'uid1' and month=202405 limit 20`

query 2 works. but query 1 get error as follow

```
InternalException: INTERNAL Error: Attempted to dereference shared_ptr that is NULL!
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

**Comment by samansmink** [comment]
Hey @watsy0007  I can't reproduce this after fiddling a bit. Would you mind trying this out with the nightly version of delta? `force install delta from core_nightly`?

If the problem then persists, would you mind sharing the data or at least the schema of the data?

**Comment by watsy0007** [comment]
thank you @samansmink , after `force install delta from core_nightly`, it works now!
