### ISSUE TITLE
Delta table in Azure ADLS: Error interacting with object store: Generic MicrosoftAzure error: Error performing token request

### ISSUE THREAD

**Issue by gdubya** [duckdb/duckdb_delta#64]
I'm getting an error when trying to read a Delta table from an ADLS Gen2 account:

Script:
```
INSTALL azure;
LOAD azure;

INSTALL delta;
LOAD delta;

CREATE SECRET secret1 (
    TYPE AZURE,
    PROVIDER CREDENTIAL_CHAIN,
    ACCOUNT_NAME 'mystorageaccount'
);

SELECT count(*) FROM delta_scan('abfss://mycontainer/delta-example');
```

Error:

> IO Error: Hit DeltaKernel FFI error (from: While trying to read from delta table: 'abfss://mycontainer/delta-example/'): Hit error: 8 (ObjectStoreError) with message (Error interacting with object store: Generic MicrosoftAzure error: Error performing token request: Error after 10 retries in 1.9087799s, max_retries:10, retry_timeout:180s, source:error sending request for url (http://169.254.169.254/metadata/identity/oauth2/token?api-version=2019-08-01&resource=https%3A%2F%2Fstorage.azure.com))

Reproduced in both Windows and WSL. Maybe it's something related to the network settings here, but I'm sure this has worked in earlier versions...

**Comment by gdubya** [comment]
Reading parquet files from the same folder works fine, indicating that it's a Delta problem rather than Azure:

```
SELECT count(*) FROM read_parquet('abfss://hrz-test1/delta-example/*.parquet');
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│         1440 │
└──────────────┘
```

**Comment by gdubya** [comment]
Using latest versions: 
```
D update extensions;

100% ▕████████████████████████████████████████████████████████████▏
┌────────────────┬────────────┬─────────────────────┬──────────────────┬─────────────────┐
│ extension_name │ repository │    update_result    │ previous_version │ current_version │
│    varchar     │  varchar   │       varchar       │     varchar      │     varchar     │
├────────────────┼────────────┼─────────────────────┼──────────────────┼─────────────────┤
│ azure          │ core       │ NO_UPDATE_AVAILABLE │ 49b63dc          │ 49b63dc         │
│ httpfs         │ core       │ NO_UPDATE_AVAILABLE │ 1f98600c2c       │ 1f98600c2c      │
│ delta          │ core       │ NO_UPDATE_AVAILABLE │ v0.1.0           │ v0.1.0          │
└────────────────┴────────────┴─────────────────────┴──────────────────┴─────────────────┘
```

**Comment by samansmink** [comment]
Hi @gdubya thanks for reporting, I will take a look at this. However I'm not sure if this can be fixed easily at the current state of the delta kernel, as we have to rely on the [object_store crate](https://docs.rs/object_store/latest/object_store/) for this authentication to happen

**Comment by gdubya** [comment]
Oh, ok. I'm not sure that I understand. Is it more complicated than what I suggest in https://github.com/duckdb/duckdb_delta/pull/65 ? (maybe not an ideal solution but a quick fix for this particular issue)

**Comment by samansmink** [comment]
I think that would break things if you want the azure sdk to fetch your credentials from env vars

**Comment by gdubya** [comment]
Good point. I guess there is no urgent need for any change to the Delta plugin given that there's a workaround (explicitly define the CHAIN in the secret). Thanks for the input!
