### ISSUE TITLE
delta_scan cannot read from delta tables starting with uppercase letter.

### ISSUE THREAD

**Issue by mrjsj** [duckdb/duckdb_delta#7]
Platform: MacOS ARM64

DuckDB version: 0.10.3

Trying to read a delta tabel with capital letter results in error:
```
D select * from delta_scan('file:///Users/jsj/Downloads/Pipelines');
IO Error: Hit DeltaKernel FFI error (from: snapshot in DeltaScanScanBind): Hit error: 15 (MissingVersionError) with message (No table version found.)
```

It works fine with the following delta table names:
- pipelines
- p**I**pelines (uppercase I after first p)
- pipeline**S** (uppercase S)
- p**IPELINES** (all capital except first p)

**Comment by mrjsj** [comment]
Update: 

It works if I put a backslash after the table name, e.g. 
```
select * from delta_scan('file:///Users/jsj/Downloads/Pipelines/');
```

I have tried making the unit tests fail in delta-kernel-rs by making the the delta tables upper-case, but no issue there (or I'm not proficient enough in Rust).

**Comment by mrjsj** [comment]
Great, thank you!

**Comment by samansmink** [comment]
Should be fixed now, please let me know if it isn't!

**Comment by Monofascia** [comment]
Same problem for me, check if the path doesn't contain any names with spaces like for example
C:\Users\P.Iezzi\Desktop\TUTTO\Corsi\**Azure DELTA Lake**\deltalake_mockaroo
