### ISSUE TITLE
Azure ADLS Gen2 with HNS: Unable to delta_scan FQDN abfss URL

### ISSUE THREAD

**Issue by gdubya** [duckdb/duckdb_delta#71]
Using a FQDN HNS hostname causes an error.

For example (where the secret has already been configured for `mystorageaccount`), this works:

> select count(*) from delta_scan('abfss://mycontainer/mydelta');

But this fails with a "bad request" error:

> select count(*) from delta_scan('abfss://mycontainer@mystorageaccount.dfs.core.windows.net/mydelta');

I think the code for determining the `bucket` variable needs to be updated (around line 173)?
        
```
        auto end_of_fqdn_container = path.find('@', 8);
        // An abfs(s) URL may contain the FQDN for the storage account 
        // e.g. "abfss://container@storage.dfs.core.windows.net/some/path"
        if (StringUtil::StartsWith(path, "abfss://") && (end_of_fqdn_container != string::npos) {
            bucket = path.substr(8, end_of_fqdn_container-8);
        } else {
            bucket = path.substr(8, end_of_container-8);
        }
```

Also the "azure_endpoint" is being hard-coded to `https://" + account_name + ".**blob**.core.windows.net/` instead of `.dfs.`. I guess the `endpoint` builder option does not need to be set when a FQDN is used? or, if endpoint is empty or null then use the value of the  duckdb `azure_endpoint` variable? (`select current_setting('azure_endpoint');`)

I'm having trouble setting up my local environment for developing and testing the extension myself so this is currently just guesswork.

**Comment by samansmink** [comment]
Will close this one as it is fixed on nightlies now and scheduled for release in upcoming duckdb v1.1.0 release
