### ISSUE TITLE
DeltaKernel FFI error when reading Delta table

### ISSUE THREAD

**Issue by akhil-leen** [duckdb/duckdb_delta#75]
## Overview
I'm encountering a DeltaKernel FFI error when trying to read from a Delta table. The error suggests there are null values in a non-nullable field, but my checks indicate this isn't the case.

I'm using [DLT](https://dlthub.com/docs/intro) to write data to filesystem (local/ s3) in the delta format with `append` write disposition.

I'm then trying to query the data in the new table using duckdb + delta extension using the `_dlt_load_id` to always query the latest batch of data. 

## Error 

Query:

```sql
SELECT * FROM delta_scan('./dlt_output/dataset_name/table_name/')  WHERE _dlt_load_id = '1724979078.9177752';
```

```sh
-- IO Error: Hit DeltaKernel FFI error (from: While trying to read from delta table: 'file:///Users/akhil/scratchpad/dlt_output/dataset_name/table_name/'): Hit error: 2 (ArrowError) with message (Json error: whilst decoding field 'minValues': Encountered unmasked nulls in non-nullable StructArray child: Field { name: "_dlt_load_id", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} })
```

## Additional information
I've verified that there are no null values in the _dlt_load_id column:

```sql
SELECT COUNT(*) as total_rows, COUNT(_dlt_load_id) as rows_with_load_id
FROM delta_scan('./dlt_output/dataset_name/table_name/')
```

Result:
```
┌────────────┬───────────────────┐
│ total_rows │ rows_with_load_id │
│   int64    │       int64       │
├────────────┼───────────────────┤
│       1000 │              1000 │
└────────────┴───────────────────┘
```

This shows that all 1000 rows have a non-null _dlt_load_id.

Thank you for your help in resolving this issue. Let me know if there is any additional information or diagnostics I can provide to help troubleshoot this.

**Comment by akhil-leen** [comment]
Closing this issue, we still think that there is an issue with duckdb reading delta table with `load_id` - the issue might be related to some delta metadata (`minValues` in the delta log).

We didn't have enough time to go deep into this, but we switched over to use polars instead (`pl.scan_delta`) and we were able to read the data with no problems. 

Feel free to reopen the issue if you run into the same.

**Comment by baptvit** [comment]
@akhil-leen  I found my self having the same issue while I was trying query from delta table using the `delta_scan()`.

For me worked explicitly set the s3 credentials:

```python
conn.execute("""
    CREATE SECRET (
        TYPE s3,
        KEY_ID '<value>',
        SECRET '<value>',
        SESSION_TOKEN '<value>',
        REGION '<value>'
        );
""") 
```
