### ISSUE TITLE
delta stopped working in 1.1

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb_delta#81]
using 1.1, when i scan a delta table i get this error

```
Error: An error occurred while trying to automatically install the required extension 'delta':
Failed to download extension "delta" at URL "http://extensions.duckdb.org/v1.1.0/linux_amd64_gcc4/delta.duckdb_extension.gz" (HTTP 403)
Extension "delta" is an existing extension.
```

**Comment by gislawill** [comment]
I am seeing this as well for linux arm64 (`http://extensions.duckdb.org/v1.1.0/linux_arm64/delta.duckdb_extension.gz`). Seeing a 403 at the url instead of the download that I see at http://extensions.duckdb.org/v1.0.0/linux_arm64/delta.duckdb_extension.gz

**Comment by carlopi** [comment]
Can you give this another try?

Linux builds for duckdb_delta were lagging behind schedule, sorry for the wait.

**Comment by djouallah** [comment]
thanks, it is working now
