### ISSUE TITLE
Hit error: 15 (MissingVersionError) with message (No table version found.)

### ISSUE THREAD

**Issue by bali1285** [duckdb/duckdb_delta#95]
Hey there, 

I have similar issue to: https://github.com/duckdb/duckdb_delta/issues/7

I'm hitting 'No Table version found'. Below is the .py code that i played with that gives me the error.  Error below as well

IOException: IO Error: Hit DeltaKernel FFI error (from: While trying to read from delta table: '[file://c:\Users\user.name\folder\my_delta_table/'): Hit error: 15 (MissingVersionError) with message (No table version found.)

import duckdb
from deltalake import DeltaTable, write_deltalake
con = duckdb.connect()
con.execute("INSTALL delta;")
con.execute("LOAD  delta;")
df1 = con.query("SELECT i AS id, i % 2 AS part, 'value-' || i AS value FROM range(0, 5) tbl(i)").df()
df2 = con.query("SELECT i AS id, i % 2 AS part, 'value-' || i AS value FROM range(5, 10) tbl(i)").df()
write_deltalake(f"./my_delta_table", df1,  partition_by=["part"])
write_deltalake(f"./my_delta_table", df2,  partition_by=["part"], mode='append')

df = con.query("""
SELECT *
FROM delta_scan('./my_delta_table/')
ORDER BY id;
                  """).df()

**Comment by samansmink** [comment]
Sorry for the late reply here, but I can no longer reproduce this issue so im kindof assuming this works as expected now. Note that im using the same package in the `scripts/generate_test_data.py` script that is used to test against. Please feel free to reopen if the issue persists!

**Comment by samansmink** [comment]
ah my bad, I realize now that this is likely a windows-specific issue. It appears to be a similar issue to https://github.com/duckdb/duckdb_delta/issues/103. So I will keep it closed as a duplicate: please check in with the other issue for progress!

**Comment by Monofascia** [comment]
Same problem for me, check if the path doesn't contain any names with spaces like for example
C:\Users\P.Iezzi\Desktop\TUTTO\Corsi\ Azure DELTA Lake \deltalake_mockaroo
